language: android
jdk: oraclejdk8
env:
  matrix:
  - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
android:
  components:
  - android-19
  - build-tools-19.1.0
  - extra-google-m2repository
  - extra-android-m2repository
script: ./gradlew --info clean assemble test
